//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCHET
{
    using System;
    using System.Collections.Generic;
    
    public partial class analy
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int added { get; set; }
        public int deleted { get; set; }
        public int user_id { get; set; }
        public int updated { get; set; }
    
        public virtual user user { get; set; }
    }
}
