//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCHET
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Plategi
    {
        public int id { get; set; }
        public string Payment_name { get; set; }
        public int count { get; set; }
        public decimal price { get; set; }
        public decimal sum { get; set; }
        public string Category { get; set; }
        public System.DateTime date { get; set; }
        public int User_id { get; set; }
    }
}
